services:
  api:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    ports:
      - "8081:8080"
    volumes:
      - ./api:/var/www/api
    command: ["php", "-S", "0.0.0.0:8080", "-t", "/var/www/api", "/var/www/api/router.php"]
    environment:
      - PHP_CLI_SERVER_WORKERS=4
